# Generated by Django 5.1.6 on 2025-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'новостройка'), (False, 'старое здание'), (None, 'не заполнено')], null=True),
        ),
    ]
