# Generated by Django 5.1.6 on 2025-03-01 14:56

from django.db import migrations
import phonenumbers

def add_pure_phone_number(apps,schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = f"+7{phonenumbers.parse(flat.owners_phonenumber,'RU').national_number}"
        valid_phone = phonenumbers.parse(pure_phone,"RU")
        if phonenumbers.is_valid_number(valid_phone):
            flat.owner_pure_phone = valid_phone
            flat.save()
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(add_pure_phone_number)
    ]
