# Generated by Django 5.1.6 on 2025-03-02 15:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250301_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fio', models.CharField(max_length=20)),
                ('owner_phone_numer', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца')),
                ('flat', models.ManyToManyField(blank=True, related_name='owned_flats', to='property.flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
